BotSelfConfig:
  host: "127.0.0.1"
  port: 20000
  debug: false
  superusers: ["123456789"]
  nickname: ["ATRI", "Atri", "atri", "亚托莉", "アトリ"]
  command_start: ["", "/"]
  command_sep: ["."]
  session_expire_timeout: 60

SauceNAO:
  key: ""
